### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by AlwaysAtonal** [UNICKCHENG/chatglm-fastapi#1]
Add Dockerfile like this

```dockerfile
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

ADD ./app /app
ADD requirements.txt /app/requirements.txt

WORKDIR /app

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install python3 python3-pip -y \
    && apt-get autoclean && rm -rf /var/lib/apt/lists/*

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt --no-cache-dir \
    && rm -rf /root/.cache/pip/*

CMD ["python3","main.py"]
```

Build image

```shell
docker build -t chatglm2:api-beta-0.0.1 .
```

Add docker-compose.yml like this

```yaml
version: "3.9"

services:
  chatglm2-6b-openai:
    image: chatglm2:api-beta-0.0.1
    ports:
    - 8000:8000
    volumes:
    - ./env:/app/.env
    - ./model:/model
    restart: always
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0","1","2","3"]
            capabilities: [gpu]
```
